language: node_js
os: linux
node_js:
  - lts/*
install:
  - yarn install # npm ci
jobs:
  include:
    - stage: "npm publish"
      script:
        - yarn lib
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_API_KEY
        cleanup: true
        on:
          branch: master
    - stage: "deploy pages"
      script:
        - yarn docs:build # npm run docs:build
      deploy:
        provider: pages
        cleanup: false
        local_dir: examples/docs/.vuepress/dist
        token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
        keep_history: true
        target_branch: gh-pages
        on:
          branch: master
