language: node_js
os: linux
node_js:
  - lts/*
install:
  - yarn install # npm ci
jobs:
  include:
    - stage: "npm publish"
      script:
        - yarn lib
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_API_KEY
        skip_cleanup: true
        on:
          branch: master
    - stage: "deploy pages"
      script:
        - yarn docs:build # npm run docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: examples/docs/.vuepress/dist
        github_token: $GITHUB_TOKEN 
        keep_history: true
        target_branch: gh-pages
        on:
          branch: master
